Fix get_environment() for later versions of RouterOS
napalm-automation-community/napalm-ros pull request #101
Opened 2022-08-11 18:04 UTC by washcroft

As per title, the output of /system/health/print changed in later versions of RouterOS

2022-08-13 18:42 UTC, luqasz commented
Describe what changes and how.
Fix formatting.
Tests have to pass for both old and newer versions.

2022-08-14 11:59 UTC, washcroft commented
Done. I've simply updated the test data to reflect the latest version (the mocked one is >7 years old, I'll leave that to you/somebody else to support if they really want to).

2022-08-14 17:57 UTC, luqasz requested changes
Please review suggestions and comments.
Since given command outputs are for `CCR2004-16G-2S+`, please move `tests/unit/mocked_data/test_get_environment/pc` to `tests/unit/mocked_data/test_get_environment/CCR2004-16G-2S+`
I will take care of PC data myself. Everything else LGTM.

2022-08-14 17:57 UTC, luqasz commented on napalm_ros/ros.py
> +            name = system_resource.get('cpu', 'Unknown') + ' ' + cpu_values['cpu']
```suggestion
            name = cpu_values['cpu']
```
Use unified names for cpus. Otherwise it will differ in architectures.

2022-08-14 17:57 UTC, luqasz commented on napalm_ros/ros.py
> +        for entry in system_health:
```suggestion
        for entry in self.api('/system/health/print'):
```
No need for line 308.

2022-08-14 17:57 UTC, luqasz commented on napalm_ros/ros.py
> +            system_health = self.api('/system/health/print')
```suggestion
```

2022-08-14 17:57 UTC, luqasz commented on tests/unit/mocked_data/test_get_environment/pc/_system_health_print.json
> +    {
Did you get this data from a real device ? I'm asking since official [docs](https://help.mikrotik.com/docs/display/ROS/Health) state something different. Or docs are outdated ?

2022-08-15 16:25 UTC, washcroft commented on tests/unit/mocked_data/test_get_environment/pc/_system_health_print.json
> +    {
Yes, straight off a real device - CCR2004-16G-2S+ running RouterOS 7.4

2022-08-15 16:29 UTC, washcroft commented
> Please review suggestions and comments. Since given command outputs are for `CCR2004-16G-2S+`, please move `tests/unit/mocked_data/test_get_environment/pc` to `tests/unit/mocked_data/test_get_environment/CCR2004-16G-2S+` I will take care of PC data myself. Everything else LGTM.

All done

2022-08-16 10:29 UTC, luqasz approved these changes

2022-08-16 10:30 UTC, merged