Support additional SSL context parameters
napalm-automation-community/napalm-ros pull request #103
Opened 2022-08-14 11:00 UTC by washcroft

**New optional_args for Netbox**
- When **netbox_default_ssl_params** is set to True:
- - **verify_certificate** - if specified and set to False (default is True), the MikroTik certificate will not be checked for trust, meaning the common name doesn't need to match the device being connected to, and the issuing CA doesn't need to be trusted (use this if the certificate is set to none in the api-ssl service on the MikroTik)
- - **check_hostname** - if specified and set to False (default is True unless the device being connected to is via IP Address not Hostname), the certificate common name doesn't need to match the device being connected to
- - **ca_certificate** - if specified (as a Base64 string e.g. `Mw9THGWGW........saW6Ttg==`), the MikroTik certificate will be checked it has been issued by this CA
- **username** and **password** - allows overriding the otherwise global NAPALM credentials with device specific credentials (Netbox limitation)

2022-08-14 18:49 UTC, luqasz requested changes
I am not familiar with how netbox can pass parameters into napalm driver. I must say I am confused about logic on how and when certs need to verified etc.
I'd like to help but I need to know:
* how netbox passes params into napalm driver
* how does username, password work in netbox (it seems redundant to use `optional_args` to pass them)

2022-08-14 18:49 UTC, luqasz commented on napalm_ros/ros.py
> +        self.password = self.optional_args.get('password', password)
```suggestion
```
Both params are in 56,57.

2022-08-14 18:49 UTC, luqasz commented on napalm_ros/ros.py
> +            ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
Why?

2022-08-15 16:35 UTC, washcroft commented on napalm_ros/ros.py
> +        self.password = self.optional_args.get('password', password)
You have to specify a NAPALM Username and Password globally, for the entire Netbox instance, but you can specify optional_args on a per device/platform basis. This provides a mechanism to use per device usernames/passwords instead of the global credentials.

2022-08-15 16:37 UTC, washcroft commented on napalm_ros/ros.py
> +            ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
This relates to certificate validation, it tells the SSL wrapper we are connecting to a server and should expect a server certificate (not a client certificate) from the other end. It is ignored if disabling certificate validation.

2022-08-16 17:14 UTC, luqasz commented
So netbox passes params in optional_args per device group or for single one ?

2022-08-23 10:24 UTC, washcroft commented
> So netbox passes params in optional_args per device group or for single one ?

Per device "platform", you can use that to group devices, or use per device if you wish.

2022-10-23 06:30 UTC, washcroft commented
Do you want me to do anything further with this?

2022-10-23 18:19 UTC, luqasz commented
Sorry for not responding.
After revisiting and rereading all netbox specific features, I have some thoughts. `napalm-ros` allows for passing ssl contexts as well as username and password. There is no need to add custom logic `if netbox` things. It is just a matter of time when some one comes and asks to change e.g. ssl context because they don't use host cert verification while someone wants to use it. 

I'd prefer for netbox (and others) to use already existing functionality. Please contact netbox developers and override any required params there.

2022-12-29 19:53 UTC, closed without merging

2025-01-17 15:03 UTC, felbinger commented
So is there a way to skip the certificate check with netbox? I couldn't find anything in the docs of the netbox plugin... @washcroft