Allow connections via tls
napalm-automation-community/napalm-ros pull request #87
Opened 2022-01-17 15:41 UTC by sHorst

- Allow connection to ssl api. 
- Defaults to not secure
- If hostname is IP, do not validate Hostname

2022-01-18 14:41 UTC, luqasz requested changes

2022-01-18 14:41 UTC, luqasz commented on napalm_ros/ros.py
> +            if self.secure:
I'd prefer to pass `ctx` as a callable in `optional_args` Use cases vary and I don't want to assume some use case here.

2022-01-18 15:58 UTC, sHorst commented on napalm_ros/ros.py
> +                    parent_interface=iface.child,
fair enouph

2022-01-18 15:58 UTC, sHorst commented on napalm_ros/ros.py
> +            if self.secure:
worked in

2022-01-18 20:17 UTC, luqasz requested changes
1. I'd rather go with `ssl_wrapper` param. End user is responsible of providing that, since there are many use cases.
2. Move code related to `lldp_neighbours` into separate PR

2022-01-18 20:17 UTC, luqasz commented on napalm_ros/ros.py
> -        self.port = self.optional_args.get('port', 8728)
Leave as it is.

2022-01-18 20:17 UTC, luqasz commented on napalm_ros/ros.py
> +        self.secure = self.optional_args.get('secure', False)
No ned for that. 
```python
# It is end user responsibility to provide that wrapper. Examples on how to connect with TLS/SSL are given in librouteros docs.
self.ssl_wraper = optional_args.get('ssl_wraper', librouteros.DEFAULTS['ssl_wraper'])
```

2022-01-18 20:17 UTC, luqasz commented on napalm_ros/ros.py
> -                login_method=method,
```python
ssl_wrapper=self.ssl_wrapper
```

2022-01-18 20:17 UTC, luqasz commented on napalm_ros/ros.py
> +            if self.secure:
No need for that. See `ssl_wrapper` param above.

2022-01-18 20:17 UTC, luqasz commented on napalm_ros/ros.py
> +        if ',' in string:
Please add those changes in separate PR

2022-01-19 08:45 UTC, sHorst commented
ad 1: would be nice, if you say so in the first comment :) ..
ad 2: what is the reasoning behind that? except "clean" code/PR (will see how i can manage this on github)

2022-01-19 09:04 UTC, sHorst commented on napalm_ros/ros.py
> +        self.secure = self.optional_args.get('secure', False)
I am using Netbox, which in turn uses napalm form connecting to devices. 
Netbox does only allow me to set optional_args as json, but i cannot create an ssl wrapper there.

2022-01-19 09:05 UTC, sHorst commented on napalm_ros/ros.py
> -        self.port = self.optional_args.get('port', 8728)
the port will change when using SSL

2022-01-19 09:27 UTC, sHorst commented
Soo .. I factored the LLDP_neigbour code out. and will create a second merge request.
For the ssl_wraper, i moved it to a optiona_args. But since netbox does not allow to give the SSL context in, i used a generate_ssl_wraper optional argument, to generate it here.

2022-01-19 10:09 UTC, sHorst commented on napalm_ros/ros.py
> +        self.secure = self.optional_args.get('secure', False)
added a generate_ssl_wraper optional argument here. so this schould be more condensed.

2022-01-21 11:09 UTC, luqasz commented
Thx for PR. I will look at it closer in few days. Now I know that you are using this with netbox, clarifies and complicates things.

2022-01-27 21:44 UTC, luqasz commented on napalm_ros/ros.py
> +        if self.optional_args.get('generate_ssl_wraper', False):
```python
if self.optional_args.get('generate_ssl_wraper', False):
```
makes more sense since we want to generate it instead of using a provided one. `generate` in name implies that it will be generated.

2022-01-27 21:45 UTC, luqasz commented on napalm_ros/ros.py
> -        self.port = self.optional_args.get('port', 8728)
No. Leave it as is. See below comment why.

2022-01-27 22:00 UTC, luqasz commented on napalm_ros/ros.py
> +        if self.optional_args.get('generate_ssl_wraper', False):
Here you can set port to default ssl 8729

2022-01-27 22:05 UTC, luqasz commented on napalm_ros/ros.py
> +        self.port = self.optional_args.get('port', 8729 if 'ssl_wraper' in self.optional_args else 8728)
Remove this line. Use one which is on line [L53](https://github.com/napalm-automation-community/napalm-ros/pull/87/files#diff-a4937ea7b7aaf5bbe154be361eb797642478ea6abfe150dfe7d9c19340b7234eL53)

2022-01-28 17:30 UTC, sHorst commented on napalm_ros/ros.py
> +        self.port = self.optional_args.get('port', 8729 if 'ssl_wraper' in self.optional_args else 8728)
I do not quite get, why you do not like the port switch. if ssl is used the default port is 8729 and not 8728, even when the ssl_wrapper is set manualy :) .. but can do the rework here .. This is not a netbox thing, but a ssl logic of the switch.

2022-01-28 23:14 UTC, luqasz commented on napalm_ros/ros.py
> +        self.port = self.optional_args.get('port', 8729 if 'ssl_wraper' in self.optional_args else 8728)
Eh silly me. I didn't read with understanding. This line is correct.

2022-01-28 23:17 UTC, luqasz commented on napalm_ros/ros.py
> +        self.port = self.optional_args.get('port', 8729 if 'ssl_wraper' in self.optional_args else 8728)
Ok you are right. This line is correct. I didn't get it first time.

2022-02-06 12:09 UTC, sHorst commented on napalm_ros/ros.py
> +        if self.optional_args.get('generate_ssl_wraper', False):
I renamed the generate_ssl_wrapper to netbox_default_ssl_params. The False makes sense, or do you want to generate the wrapper, if it is not set?

2022-02-06 17:34 UTC, luqasz approved these changes

2022-02-06 17:35 UTC, merged

2022-06-08 02:24 UTC, geoffdavis commented on napalm_ros/ros.py
> +        if self.optional_args.get('generate_ssl_wraper', False):
@luqasz I know this has been merged already, but I'm awfully confused here... What in particular makes using the TLS/SSL version of the RouterOS API Netbox-dependent?

As far as I can tell, the TLS functionality is completely separate from any sort of Netbox interaction. Am I missing something?

2022-06-13 13:45 UTC, luqasz commented on napalm_ros/ros.py
> +        if self.optional_args.get('generate_ssl_wraper', False):
@geoffdavis I don't quite understand your question.