Update ros.py to support CHR
napalm-automation-community/napalm-ros pull request #93
Opened 2022-04-28 10:21 UTC by nunomcruz

Previous implementation supposed there was always a routerboard method, however this isn't true for CHR, where a serial number isn't also available.

2022-04-29 22:21 UTC, luqasz commented
Hi. 

Sorry for my delayed reply. I will look at this closer in few days.

2022-04-29 22:22 UTC, luqasz requested changes

2022-04-29 22:22 UTC, luqasz commented on napalm_ros/ros.py
> +    def get_config(self,retrieve='all', full=False, sanitized=False):
Please split this into separate PR

2022-04-30 15:06 UTC, nunomcruz commented on napalm_ros/ros.py
> +    def get_config(self,retrieve='all', full=False, sanitized=False):
Just reverted it, check if it's ok.

2022-05-08 20:39 UTC, luqasz requested changes

2022-05-08 20:39 UTC, luqasz commented on napalm_ros/ros.py
> -        routerboard = tuple(self.api('/system/routerboard/print'))[0]
Which exception is raised ? 
I'd prefer to use try, except here.

```python
try:
    routerboard = tuple(self.api('/system/routerboard/print'))[0]
except EXC:
    routerboard = dict()
```

2022-05-08 20:39 UTC, luqasz commented on napalm_ros/ros.py
> +        if  resource['board-name'] == 'CHR':
Fix formatting.

2022-05-09 14:24 UTC, nunomcruz commented on napalm_ros/ros.py
> -        routerboard = tuple(self.api('/system/routerboard/print'))[0]
I agree with you but I was following the same style as other functions where self.api is called. I think that in this case get_facts should follow the same style as other functions, don't you agree? The same happens with other drivers (at least on srlinux and vyos), no exception handling is done during command calls. It's only performed during the connect phase.

2022-05-18 17:30 UTC, luqasz commented
@nunomcruz Please rebase. I'fe fixed get_interfaces() error.

2022-06-13 14:04 UTC, luqasz commented
Please update to newest master. I've fixed pylint errors.

2022-10-20 22:00 UTC, closed without merging